services:
  mongo:
    deploy:
      resources:
        limits:
          memory: 512M

  rabbitmq:
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 128M
